---
################################################################################
#
#   Crypto Config for Delivery Tracking Network
#
################################################################################

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    Users:
      Count: 1

PeerOrgs:
  - Name: DeliveryOrg
    Domain: delivery.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
